[ERROR] 2020-11-18 15:55:45,124 | /home/anil/medley/apps/frappe/frappe/app.py:
Site: ordermedicines
Form Dict: {
 "cmd": "erpnext.selling.page.point_of_sale.point_of_sale.get_items",
 "item_group": "All Item Groups",
 "page_length": "40",
 "search_value": "",
 "start": "0"
}
Request Error
Traceback (most recent call last):
  File "/home/anil/medley/apps/frappe/frappe/app.py", line 64, in application
    response = frappe.api.handle()
  File "/home/anil/medley/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/anil/medley/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/anil/medley/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/anil/medley/apps/frappe/frappe/__init__.py", line 1064, in call
    return fn(*args, **newargs)
TypeError: get_items() missing 1 required positional argument: 'price_list'
[ERROR] 2020-11-18 15:55:46,199 | /home/anil/medley/apps/frappe/frappe/app.py:
Site: ordermedicines
Form Dict: {
 "cmd": "erpnext.regional.india.utils.get_regional_address_details",
 "company": "Medley",
 "doctype": "Sales Invoice",
 "party_details": "{\"shipping_address\":\"\",\"shipping_address_name\":\"\",\"customer_address\":\"\"}",
 "return_taxes": "1"
}
Request Error
Traceback (most recent call last):
  File "/home/anil/medley/apps/frappe/frappe/app.py", line 64, in application
    response = frappe.api.handle()
  File "/home/anil/medley/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/anil/medley/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/anil/medley/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/anil/medley/apps/frappe/frappe/__init__.py", line 1064, in call
    return fn(*args, **newargs)
  File "/home/anil/medley/apps/erpnext/erpnext/regional/india/utils.py", line 162, in get_regional_address_details
    get_tax_template_for_sez(party_details, master_doctype, company, 'Customer')
  File "/home/anil/medley/apps/erpnext/erpnext/regional/india/utils.py", line 229, in get_tax_template_for_sez
    gst_details = frappe.db.get_value(party_type, {'name': party_details.get(frappe.scrub(party_type))},
  File "/home/anil/medley/apps/frappe/frappe/database/database.py", line 400, in get_value
    ret = self.get_values(doctype, filters, fieldname, ignore, as_dict, debug,
  File "/home/anil/medley/apps/frappe/frappe/database/database.py", line 445, in get_values
    out = self._get_values_from_table(fields, filters, doctype, as_dict, debug, order_by, update)
  File "/home/anil/medley/apps/frappe/frappe/database/database.py", line 590, in _get_values_from_table
    r = self.sql("select {0} from `tab{1}` {2} {3} {4}"
  File "/home/anil/medley/apps/frappe/frappe/database/database.py", line 156, in sql
    self._cursor.execute(query, values)
  File "/home/anil/medley/env/lib/python3.8/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/home/anil/medley/env/lib/python3.8/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/home/anil/medley/env/lib/python3.8/site-packages/pymysql/connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/anil/medley/env/lib/python3.8/site-packages/pymysql/connections.py", line 732, in _read_query_result
    result.read()
  File "/home/anil/medley/env/lib/python3.8/site-packages/pymysql/connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "/home/anil/medley/env/lib/python3.8/site-packages/pymysql/connections.py", line 684, in _read_packet
    packet.check_error()
  File "/home/anil/medley/env/lib/python3.8/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/home/anil/medley/env/lib/python3.8/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.InternalError: (1054, "Unknown column 'gst_category' in 'field list'")
[ERROR] 2020-11-18 17:13:13,114 | /home/anil/medley/apps/frappe/frappe/app.py:
Site: ordermedicines
Form Dict: {
 "cmd": "erpnext.selling.page.point_of_sale.point_of_sale.get_items",
 "item_group": "All Item Groups",
 "page_length": "40",
 "search_value": "",
 "start": "0"
}
Request Error
Traceback (most recent call last):
  File "/home/anil/medley/apps/frappe/frappe/app.py", line 64, in application
    response = frappe.api.handle()
  File "/home/anil/medley/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/anil/medley/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/anil/medley/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/anil/medley/apps/frappe/frappe/__init__.py", line 1064, in call
    return fn(*args, **newargs)
TypeError: get_items() missing 1 required positional argument: 'price_list'
[ERROR] 2020-11-18 17:13:14,240 | /home/anil/medley/apps/frappe/frappe/app.py:
Site: ordermedicines
Form Dict: {
 "cmd": "erpnext.regional.india.utils.get_regional_address_details",
 "company": "Medley",
 "doctype": "Sales Invoice",
 "party_details": "{\"shipping_address\":\"\",\"shipping_address_name\":\"\",\"customer_address\":\"\"}",
 "return_taxes": "1"
}
Request Error
Traceback (most recent call last):
  File "/home/anil/medley/apps/frappe/frappe/app.py", line 64, in application
    response = frappe.api.handle()
  File "/home/anil/medley/apps/frappe/frappe/api.py", line 59, in handle
    return frappe.handler.handle()
  File "/home/anil/medley/apps/frappe/frappe/handler.py", line 24, in handle
    data = execute_cmd(cmd)
  File "/home/anil/medley/apps/frappe/frappe/handler.py", line 64, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/anil/medley/apps/frappe/frappe/__init__.py", line 1064, in call
    return fn(*args, **newargs)
  File "/home/anil/medley/apps/erpnext/erpnext/regional/india/utils.py", line 162, in get_regional_address_details
    get_tax_template_for_sez(party_details, master_doctype, company, 'Customer')
  File "/home/anil/medley/apps/erpnext/erpnext/regional/india/utils.py", line 229, in get_tax_template_for_sez
    gst_details = frappe.db.get_value(party_type, {'name': party_details.get(frappe.scrub(party_type))},
  File "/home/anil/medley/apps/frappe/frappe/database/database.py", line 400, in get_value
    ret = self.get_values(doctype, filters, fieldname, ignore, as_dict, debug,
  File "/home/anil/medley/apps/frappe/frappe/database/database.py", line 445, in get_values
    out = self._get_values_from_table(fields, filters, doctype, as_dict, debug, order_by, update)
  File "/home/anil/medley/apps/frappe/frappe/database/database.py", line 590, in _get_values_from_table
    r = self.sql("select {0} from `tab{1}` {2} {3} {4}"
  File "/home/anil/medley/apps/frappe/frappe/database/database.py", line 156, in sql
    self._cursor.execute(query, values)
  File "/home/anil/medley/env/lib/python3.8/site-packages/pymysql/cursors.py", line 170, in execute
    result = self._query(query)
  File "/home/anil/medley/env/lib/python3.8/site-packages/pymysql/cursors.py", line 328, in _query
    conn.query(q)
  File "/home/anil/medley/env/lib/python3.8/site-packages/pymysql/connections.py", line 517, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/anil/medley/env/lib/python3.8/site-packages/pymysql/connections.py", line 732, in _read_query_result
    result.read()
  File "/home/anil/medley/env/lib/python3.8/site-packages/pymysql/connections.py", line 1075, in read
    first_packet = self.connection._read_packet()
  File "/home/anil/medley/env/lib/python3.8/site-packages/pymysql/connections.py", line 684, in _read_packet
    packet.check_error()
  File "/home/anil/medley/env/lib/python3.8/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/home/anil/medley/env/lib/python3.8/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.InternalError: (1054, "Unknown column 'gst_category' in 'field list'")
